steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'docker.io/ashlijani021/ash-node-api:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'docker.io/ashlijani021/ash-node-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY